export const TOOLTIPS = {
  testMode: {
    on: "Test: crop/zoom/rotate only, faster processing",
    off: "Live: full background removal (consumes credits)",
  },
  quality: {
    on: "High: 600DPI - better print quality, slower export",
    off: "Flash: 300 DPI - faster export, lower quality",
  },
  resetAll: "Clear all slots, Start Fresh",
  clearAll: "Clear all images: keeps layout and settings",
  removeImage: "Remove image from slot",
  rotate90: "Rotate 90 degrees",
  toggleFitCover: "Cover mode: drag to reposition",
  toggleFitStretch: "Stretch mode: fills entire frame",
  cropAndProcess: "Crop the selected area and remove the background",
  cropTestMode: "Crop only: no API call (test mode)",
  cancel: "Discard current image and start over",
  print: "Opens in viewer to print - temporary file, auto-deleted on restart",
  printAll: "Opens merged PDF in viewer - temporary file, auto-deleted on restart",
  savePdf: "Save a permanent copy of the PDF to your chosen folder",
  startOver: "Clear result and return to image selection",
  processAll: "Crop and process all prepared slots",
  fontCycle: "Click to cycle font style",
  labelCycle: "Click to cycle label mode",
  backToSizes: "Back to size selection",
  layoutSwitch: "Switch layout (resets all slots)",
  stretchAll: "Stretch all images to fill frame (disables panning)",
  selectTemplate: "Select an SVG print template",
  uploadSignature: "Upload a signature image",
  retouch: "Open retouch editor: clone stamp and eraser",
  removeSlot: "Remove this slot",
  settings: "API keys, preferences and configuration",

  // Batch Converter
  converterTargetPng: "PNG — lossless, larger file, best for graphics / line art",
  converterTargetJpeg: "JPEG — lossy ~90 quality, smaller file, best for photos",
  converterTargetWebp: "WebP — modern, ~90 quality, smaller than JPEG/PNG",
  converterSelectAll: "Check all tiles for next Convert",
  converterDeselectAll: "Uncheck all tiles",
  converterDensity: "Adjust tile size — changes grid density",
  converterBrowse: "Browse via system dialog — pick PNG/JPEG/WebP files",
  converterDpi: "PDF render resolution — 150 fast, 200 balanced, 300 print-sharp (higher is slower)",
  pdfConverterBrowse: "Browse via system dialog — pick PDF files",
  pdfConverterDropzone: "Drop PDFs here — each page expands to one tile",
  converterConvert: "Convert checked images to target format in a timestamped folder",
  converterConvertDisabled: "Select at least one image to convert",
  converterOpenFolder: "Reveal batch folder in file manager",
  converterTileCheck: "Include in next Convert — unchecked tiles are skipped",
  converterTileRemove: "Remove from batch (does not delete original file)",
  converterDropzone: "Drop PNG, JPEG, or WebP here — mixed formats allowed, one target for all",

  // Retouch Window
  closeRetouch: "Close without saving",
  cloneStamp: "Copy pixels from source area: Alt+Click to set source",
  eraser: "Erase to transparent",
  undo: "Undo last stroke (Ctrl+Z)",
  retouchReset: "Reset to original image",
  zoomReset: "Reset zoom to fit (Ctrl+0)",
  brushSize: "Brush diameter: 10-100px ([ ] keys)",
  brushHardness: "Edge softness: 0% soft, 100% hard (eraser only)",
  brushOpacity: "Stroke opacity (clone tool only)",
  brightness: "Adjust image brightness",
  contrast: "Adjust image contrast",

  // Resume Builder
  resumeFillForm: "Start blank — fill fields manually",
  resumeImportJson: "Load a saved JSON — drag, browse, or paste",
  resumeGenerateTemplate: "Copy AI-fillable JSON template to clipboard",
  resumeBrowse: "View and edit previously generated resumes",
  resumeBack: "Back to Resume Builder",
  resumeTemplateSelect: "Choose layout — 1 or 2 column, with or without 35×45mm photo",
  resumeUploadPhoto: "Upload and crop photo — 35×45mm passport aspect",
  resumeClearPhoto: "Remove photo from this resume",
  resumePhotoDropzone: "Drop image, click to browse, or paste (Ctrl+V) — 35×45mm crop",
  resumePhotoZoom: "Zoom photo — drag slider or scroll wheel",
  resumePhotoChange: "Pick a different photo",
  resumePhotoConfirm: "Crop and use photo — saves to temp file",
  resumePhotoCancel: "Cancel without saving photo",
  resumePhotoClose: "Close photo editor without saving",
  resumeAddPhone: "Add another phone number field",
  resumeRemovePhone: "Remove this phone field",
  resumeAddEmail: "Add another email field",
  resumeRemoveEmail: "Remove this email field",
  resumeAddEducation: "Add education entry",
  resumeRemoveEducation: "Remove this education entry",
  resumeAddExperience: "Add work experience entry",
  resumeRemoveExperience: "Remove this experience entry",
  resumeAddBullet: "Add bullet point to this experience",
  resumeRemoveBullet: "Remove this bullet",
  resumeAddSkill: "Add skill entry",
  resumeRemoveSkill: "Remove this skill",
  resumeAddCert: "Add certification entry",
  resumeRemoveCert: "Remove this certification",
  resumeAddRef: "Add character reference",
  resumeRemoveRef: "Remove this reference",
  resumeSaveJson: "Save resume data as JSON — importable template",
  resumeGenerate: "Generate DOCX + PDF — pick save location (PDF needs LibreOffice)",
  resumeGenerateDisabled: "Enter full name to generate",
  resumeBrowseEdit: "Load this resume into the form to edit",
  resumeBrowseDelete: "Delete this resume — cannot be undone",
  resumeSearch: "Filter saved resumes by name",
  resumeImportBrowse: "Browse via system dialog — pick a JSON file",
  resumeImportPaste: "Paste JSON from clipboard — auto-validates",
  resumeImportDropzone: "Drop a .json file here — must match resume template shape",
  resumeHowTo: "How resume flow works — template, AI fill, import, generate",
} as const;

export type TooltipKey = keyof typeof TOOLTIPS;
