export const TOOLTIPS = {
  testMode: {
    on: "Test: crop/zoom/rotate only, faster processing",
    off: "Live: full background removal (consumes credits)",
  },
  quality: {
    on: "High: 600DPI - better print quality, slower export",
    off: "Flash: 300 DPI - faster export, lower quality",
  },
  resetAll: "Clear all slots, Start Fresh",
  clearAll: "Clear all images: keeps layout and settings",
  removeImage: "Remove image from slot",
  rotate90: "Rotate 90 degrees",
  toggleFitCover: "Cover mode: drag to reposition",
  toggleFitStretch: "Stretch mode: fills entire frame",
  cropAndProcess: "Crop the selected area and remove the background",
  cropTestMode: "Crop only: no API call (test mode)",
  cancel: "Discard current image and start over",
  print: "Opens in viewer to print - temporary file, auto-deleted on restart",
  printAll: "Opens merged PDF in viewer - temporary file, auto-deleted on restart",
  savePdf: "Save a permanent copy of the PDF to your chosen folder",
  startOver: "Clear result and return to image selection",
  processAll: "Crop and process all prepared slots",
  fontCycle: "Click to cycle font style",
  labelCycle: "Click to cycle label mode",
  backToSizes: "Back to size selection",
  layoutSwitch: "Switch layout (resets all slots)",
  stretchAll: "Stretch all images to fill frame (disables panning)",
  selectTemplate: "Select an SVG print template",
  uploadSignature: "Upload a signature image",
  retouch: "Open retouch editor: clone stamp and eraser",
  removeSlot: "Remove this slot",
  settings: "API keys, preferences and configuration",

  // Retouch Window
  closeRetouch: "Close without saving",
  cloneStamp: "Copy pixels from source area: Alt+Click to set source",
  eraser: "Erase to transparent",
  undo: "Undo last stroke (Ctrl+Z)",
  retouchReset: "Reset to original image",
  zoomReset: "Reset zoom to fit (Ctrl+0)",
  brushSize: "Brush diameter: 10-100px ([ ] keys)",
  brushHardness: "Edge softness: 0% soft, 100% hard (eraser only)",
  brushOpacity: "Stroke opacity (clone tool only)",
  brightness: "Adjust image brightness",
  contrast: "Adjust image contrast",
} as const;

export type TooltipKey = keyof typeof TOOLTIPS;
